# Generated by Django 3.2.8 on 2025-06-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0006_alter_comment_post'),
        ('moments', '0006_post_is_private_alter_comment_post'),
    ]

    operations = [
    ]
