# Generated by Django 3.2.8 on 2025-06-30 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0008_alter_post_content'),
        ('moments', '0008_merge_0007_merge_20250629_1542_0007_post_category'),
    ]

    operations = [
    ]
