# Generated by Django 5.0.2 on 2025-06-30 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0009_momentsimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MomentsImage',
        ),
    ]
