# Generated by Django 5.0.2 on 2025-06-30 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0010_delete_momentsimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='moments_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='moments.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
