# Generated by Django 3.2.8 on 2025-06-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0009_merge_20250630_1358'),
        ('moments', '0011_momentsimage'),
    ]

    operations = [
    ]
