# Generated by Django 5.2.3 on 2025-07-03 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0012_merge_0009_merge_20250630_1358_0011_momentsimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
