# Generated by Django 3.2.8 on 2025-07-03 15:41

from django.db import migrations, models
import moments.models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0013_remove_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momentsimage',
            name='image',
            field=models.ImageField(upload_to=moments.models.moments_image_upload_to),
        ),
    ]
