# Generated by Django 5.2.3 on 2025-07-03 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QQUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qq_openid', models.CharField(max_length=100, unique=True, verbose_name='QQ OpenID')),
                ('qq_nickname', models.CharField(blank=True, max_length=100, verbose_name='QQ昵称')),
                ('qq_avatar', models.URLField(blank=True, verbose_name='QQ头像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qq_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QQ用户',
                'verbose_name_plural': 'QQ用户',
            },
        ),
    ]
