# Generated by Django 5.0.2 on 2025-07-06 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_message_options_alter_message_content_and_more'),
        ('chat', '0007_auto_20250704_1312'),
    ]

    operations = [
    ]
