# Generated by Django 5.2.3 on 2025-06-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_summary',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_tags',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_blog',
            field=models.BooleanField(default=False, verbose_name='是否为博客'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='publish_type',
            field=models.CharField(default='private', max_length=20, verbose_name='发布到'),
        ),
    ]
