# Generated by Django 5.0.2 on 2025-07-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_blog_summary_blogpost_blog_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='last_saved_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后保存时间'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='是否草稿'),
        ),
    ]
