# Generated by Django 5.0.2 on 2025-07-01 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_blog_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
