# Generated by Django 3.2.8 on 2025-07-03 15:41

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(upload_to=blog.models.blog_image_upload_to),
        ),
    ]
