# Generated by Django 5.0.2 on 2025-06-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plaza_images/'),
        ),
    ]
