# Generated by Django 5.2.3 on 2025-06-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0005_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('daily', '日常'), ('study', '学习'), ('work', '工作'), ('travel', '旅行'), ('food', '美食'), ('sports', '运动'), ('entertainment', '娱乐'), ('other', '其他')], default='daily', max_length=20, verbose_name='类别'),
        ),
    ]
