# Generated by Django 5.0.2 on 2025-06-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0006_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
