# Generated by Django 5.0.2 on 2025-06-30 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0008_rename_postimage_plazaimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlazaImage',
            new_name='PostImage',
        ),
    ]
