# Generated by Django 3.2.8 on 2025-07-03 15:41

from django.db import migrations, models
import plaza.models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0009_rename_plazaimage_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=plaza.models.plaza_image_upload_to),
        ),
    ]
