# Generated by Django 3.2.8 on 2025-07-03 16:23

from django.db import migrations, models
import plaza.models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0010_alter_postimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=plaza.models.plaza_single_image_upload_to),
        ),
    ]
