# Generated by Django 5.0.2 on 2025-07-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0011_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='私密动态'),
        ),
    ]
