# Generated by Django 5.2.3 on 2025-07-02 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0003_userprofile_follower_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserZoneVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('userzone_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_userzone', to='user_profile.userprofile')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userzone_visited', to='user_profile.userprofile')),
            ],
            options={
                'ordering': ['-visited_at'],
                'unique_together': {('userzone_owner', 'visitor')},
            },
        ),
    ]
