# Generated by Django 5.2.3 on 2025-07-03 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0012_merge_0009_merge_20250630_1358_0011_momentsimage'),
        ('plaza', '0009_rename_plazaimage_postimage'),
        ('userzone', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserZonePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moments_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moments.post')),
                ('plaza_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plaza.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
