# Generated by Django 3.2.8 on 2025-07-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userzone', '0002_userzonepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserZonePost',
        ),
    ]
