# Generated by Django 3.2.8 on 2025-06-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', '女'), ('M', '男'), ('S', '保密')], max_length=1, verbose_name='性别'),
        ),
    ]
