# Generated by Django 5.2.3 on 2025-06-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follower_count',
            field=models.IntegerField(default=0, verbose_name='粉丝数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following_count',
            field=models.IntegerField(default=0, verbose_name='关注数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ip_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='IP位置'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='在线状态'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.CharField(blank=True, max_length=100, verbose_name='学校'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
