# Generated by Django 5.0.2 on 2025-07-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_follower_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followings', to='user_profile.userprofile', verbose_name='粉丝'),
        ),
    ]
